#if !canImport(ObjectiveC)
import XCTest

extension DecodeValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecodeValueTests = [
        ("testArray", testArray),
        ("testBool", testBool),
        ("testNested", testNested),
        ("testNull", testNull),
        ("testNumber", testNumber),
        ("testObject", testObject),
        ("testString", testString),
    ]
}

extension DecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DecoderTests = [
        ("testKeyedContainer", testKeyedContainer),
        ("testSingleValueContainer", testSingleValueContainer),
        ("testUnkeyedContainer", testUnkeyedContainer),
    ]
}

extension DynamicLookupTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicLookupTests = [
        ("testGet", testGet),
        ("testSet", testSet),
    ]
}

extension EncodeValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EncodeValueTests = [
        ("testArray", testArray),
        ("testBool", testBool),
        ("testNested", testNested),
        ("testNull", testNull),
        ("testNumber", testNumber),
        ("testObject", testObject),
        ("testString", testString),
    ]
}

extension EncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EncoderTests = [
        ("testKeyedContainer", testKeyedContainer),
        ("testSingleValueContainer", testSingleValueContainer),
        ("testUnkeyedContainer", testUnkeyedContainer),
    ]
}

extension JSONDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONDecoderTests = [
        ("testDecodable", testDecodable),
        ("testEnum", testEnum),
        ("testKeyed", testKeyed),
        ("testKeyedNested", testKeyedNested),
        ("testKeyedNestedInTheMiddle", testKeyedNestedInTheMiddle),
        ("testNestedArrayInTheMiddle", testNestedArrayInTheMiddle),
        ("testNestedArraysInTheMiddle", testNestedArraysInTheMiddle),
        ("testUnkeyed", testUnkeyed),
        ("testUnkeyedOfUnkeyed", testUnkeyedOfUnkeyed),
    ]
}

extension JSONEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONEncoderTests = [
        ("testEncodable", testEncodable),
        ("testEnum", testEnum),
        ("testKeyed", testKeyed),
        ("testKeyedInTheMiddle", testKeyedInTheMiddle),
        ("testKeyedNested", testKeyedNested),
        ("testNestedArrayInTheMiddle", testNestedArrayInTheMiddle),
        ("testNestedInTheMiddle", testNestedInTheMiddle),
        ("testUnkeyed", testUnkeyed),
        ("testUnkeyedOfUnkeyed", testUnkeyedOfUnkeyed),
    ]
}

extension JSONTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONTests = [
        ("testDecode", testDecode),
        ("testDecodeEscaped", testDecodeEscaped),
        ("testDecodeEscapedUnicode", testDecodeEscapedUnicode),
        ("testEncode", testEncode),
    ]
}

extension PublicAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PublicAPITests = [
        ("testJSONDecoder", testJSONDecoder),
        ("testJSONEncoder", testJSONEncoder),
    ]
}

extension UnkeyedDecodingContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnkeyedDecodingContainerTests = [
        ("testContainer", testContainer),
        ("testNestedContainer", testNestedContainer),
    ]
}

extension UnkeyedEncodingContainerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UnkeyedEncodingContainerTests = [
        ("testContainer", testContainer),
        ("testNestedContainer", testNestedContainer),
        ("testNull", testNull),
    ]
}

extension ValueTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValueTests = [
        ("testArray", testArray),
        ("testBoolean", testBoolean),
        ("testDouble", testDouble),
        ("testInteger", testInteger),
        ("testObject", testObject),
        ("testString", testString),
        ("testUnsigned", testUnsigned),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DecodeValueTests.__allTests__DecodeValueTests),
        testCase(DecoderTests.__allTests__DecoderTests),
        testCase(DynamicLookupTests.__allTests__DynamicLookupTests),
        testCase(EncodeValueTests.__allTests__EncodeValueTests),
        testCase(EncoderTests.__allTests__EncoderTests),
        testCase(JSONDecoderTests.__allTests__JSONDecoderTests),
        testCase(JSONEncoderTests.__allTests__JSONEncoderTests),
        testCase(JSONTests.__allTests__JSONTests),
        testCase(PublicAPITests.__allTests__PublicAPITests),
        testCase(UnkeyedDecodingContainerTests.__allTests__UnkeyedDecodingContainerTests),
        testCase(UnkeyedEncodingContainerTests.__allTests__UnkeyedEncodingContainerTests),
        testCase(ValueTests.__allTests__ValueTests),
    ]
}
#endif
